#!/bin/sh

# Detect whether Java is available on your system.
if ! command -v java -version 2>/dev/null 1>&2;
then
  echo "No Java on the system" >&2;
  exit 1;
fi

if ! [ -f quicklisp.lisp ];
then
  if command -v wget --version 2>/dev/null 1>&2;
  then
    wget -c https://beta.quicklisp.org/quicklisp.lisp
  elif command -v curl --version 2>/dev.null 1&2;
  then
    curl https://beta.quicklisp.org/quicklisp.lisp --output quicklisp.lisp
  fi
fi

if ! [ -f quicklisp.lisp ];
then
  echo "Failed to download quicklisp.lisp" >&2;
  exit 1;
fi

# Download cl-portable.lisp if it is not available.
if ! [ -f cl-portable.lisp ];
then
  if command -v wget --version 2>/dev/null 1>&2;
  then
    wget -c https://raw.githubusercontent.com/cwchentw/cl-portable/master/cl-portable.lisp
  elif command -v curl --version 2>/dev.null 1&2;
  then
    curl https://raw.githubusercontent.com/cwchentw/cl-portable/master/cl-portable.lisp --output cl-portable.lisp
  fi
fi

# Check whether cl-portable.lisp is available.
if ! [ -f cl-portable.lisp ];
then
  echo "Failed to download cl-portable.lisp" >&2;
  exit 1;
fi

# Download cl-yautils.lisp if it is not available.
if ! [ -f cl-yautils.lisp ];
then
  if command -v wget --version 2>/dev/null 1>&2;
  then
    wget -c https://raw.githubusercontent.com/cwchentw/cl-yautils/master/cl-yautils.lisp
  elif command -v curl --version 2>/dev.null 1&2;
  then
    curl https://raw.githubusercontent.com/cwchentw/cl-yautils/master/cl-yautils.lisp --output cl-yautils.lisp
  fi
fi

# Check whether cl-yautils.lisp is available.
if ! [ -f cl-yautils.lisp ];
then
  echo "Failed to download cl-yautils.lisp" >&2;
  exit 1;
fi

# Locate the path of the script itself.
root=$(dirname "$0");

if ! [ -d "$root/quicklisp" ];
then
  java -jar "$root/abcl.jar" \
       --eval "(require :abcl-contrib)" \
       --load "$root/quicklisp.lisp" \
       --eval "(load \"$root/quicklisp.lisp\")" \
       --eval "(quicklisp-quickstart:install :path \"$root/quicklisp\")" \
       --eval "(ql:quickload \"parenscript\")" \
       --eval "(quit)"
  echo "Restart $0"
  exit 0
else
  java -jar "$root/abcl.jar" \
       --noinform \
       --eval "(require :abcl-contrib)" \
       --load "$root/quicklisp/setup.lisp" \
       --load "$root/cl2js.lisp" -- "$@";
fi
