#!/bin/sh

if ! command -v sbcl --version 2>/dev/null 1>&2;
then
  echo "No SBCL on the system" >&2;
  exit 1;
fi

if ! command -v node --version 2>/dev/null 1>&2;
then
  echo "No Node.js on the system" >&2;
  exit 1;
fi

# Build `cl2js` with SBCL.
./build

CL2JS=./cl2js

for script in examples/*;
do
  echo "Test $script ..."
  $CL2JS "$script" | node >/dev/null || (
    echo "Failed while testing $script with $lisp";
    ./clean
    exit 1;
  )
done

# Clean local build
./clean